services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@172.22.0.1:5432/meucampeonato
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"